### ISSUE TITLE
Clarification on 'Simulation'

### ISSUE THREAD

**Issue by P-Tracy** [hmrc/self-assessment-api#338] opened 2017-03-06 08:18 UTC
In the email, it states that:

"The API implementation will also include functionality that will enable you to simulate the behaviour of the end points once we go live.  Please be aware that these are simulations only and the APIs provided may change once the actual functionality becomes live"

Can I just get a little more explanation of what we mean here?  I fully understand the nature of APIs is that with controlled version change there is fluctuation, but I would not expect things to change between Beta and Live in terms of behaviour?  

Is there anticipated churn between your Beta and Live as far as the implemented code goes?  How reliable and reflective of live is the test environment?

My concern is that we've already been told that we cannot test on the Live platform as no test NINO or UTR will be provided.  Which then puts the pressure on for the consumers to be provided an incredible live-like environment against which to test.  If we cannot guarantee that the test environment behaves as close to Live as possible, then we'd be going live blind.

**Comment by saurabharora80** [comment] 2017-03-07 11:40
As a API consumer you can simulate _certain_ failure scenarios across multiple APIs by using the header _'Gov-Test Scenario'_ mentioned in #341. 
Because we are simulating these _error scenarios_ in absence of a fixed spec from our backend, it has the potential to change slightly. This 'fluctuation' only applies to error scenarios simulated via the _'Gov-Test Scenario'_ header.

**Comment by P-Tracy** [comment] 2017-03-07 11:51
@saurabharora80 
Sorry - can you phrase this some other way?  I don't understand...
"Because we are simulating these error scenarios in absence of a fixed spec from our backend, it has the potential to change slightly. "

Is there any documentation, spec or explanation of this new test capability anywhere?  Have I missed something?

**Comment by saurabharora80** [comment] 2017-03-07 12:10
Let me answer your question before I attempt to rephrase. 
The error scenarios are documented along with every resource. Please refer to the 'Test data' tabular section in each resource for more details. 

Because we don't have concrete specification from the backend for certain scenarios, we are using the 'Gov-Test Scenario' header to simulate them; thus they could slightly change in the future when the concrete specification is available.

**Comment by saurabharora80** [comment] 2017-03-07 13:36
@P-Tracy Can I close this issue?

**Comment by P-Tracy** [comment] 2017-03-07 13:46
Sorry, this may not be my business, but is anyone worried about the fact that we're going live in a few weeks and there aren't concrete specifications for the implementation?  

Prior to release, do you think you will have had time to get full functional coverage, and stress and soak test this?

Reason I ask is that the UI is branded for the vendor so failures will be seen to be ours even if they lie with HMRC.... so this would be a risk.

**Comment by andyws** [comment] 2017-03-07 14:25
Reconciled not worried ... 

There is a scene in "Shakespeare in Love" where the money man looks at the producers books and asks "How can this work?", the reply comes back, "I don't know, but it always does".

I sent the message below to SDS this morning.  If Rebecca is correct my app is totally over-engineered!

`Yesterday I attended a lecture given by Rebecca Benneyworth about MTDfb.  As part of that lecture and confirmed in a brief discussion after the lecture it was her view that a standalone Excel spreadsheet constituted an acceptable form of digital record keeping as far as HMRC MTDfb is concerned.  As this does not accord with my understanding which underpins my development effort I wish to get clarity on the acceptability of standalone spreadsheets.`

**Comment by saurabharora80** [comment] 2017-03-07 15:15
@P-Tracy 
We have primarily simulated the followed failure scenarios 

_AGENT_NOT_SUBSCRIBED_
_AGENT_NOT_AUTHORIZED_
_CLIENT_NOT_SUBSCRIBED_

for all resources

**And**

_NONE_MET_
_ALL_MET_

only for Obligations resource

I don't see much change for the first 3. 

The last 2, which are only Obligations resource, may change slightly. 

As you can see most the API contract is not effected by these simulations.

**Comment by saurabharora80** [comment] 2017-03-08 11:12
@P-Tracy @andyws are you happy for me to close this issue?

**Comment by P-Tracy** [comment] 2017-03-08 11:13
Yes, thank you

**Closed** 2017-03-08 11:54 UTC
Labels: question
