### ISSUE TITLE
Endpoint to retrieve self employment obligation periods returns 404

### ISSUE THREAD

**Issue by paulvickery** [hmrc/self-assessment-api#444] opened 2017-06-08 15:27 UTC
After creating a test self-employment, we are unable to retrieve the obligation periods. While 
`https://test-api.service.hmrc.gov.uk/self-assessment/ni/{nino}/self-employments`
correctly returns a list of self-employments, and 
`https://test-api.service.hmrc.gov.uk/self-assessment/ni/{nino}/self-employments/{id}`
returns the self-employment,
`https://test-api.service.hmrc.gov.uk/self-assessment/ni/{nino}/self-employments/{id}/obligations`
for the same nino and self-employment id returns a 404.

**Comment by rakeshavasarala** [comment] 2017-06-08 19:54
The issue is now fixed. Obligations end-point should return correct response.

**Closed** 2017-06-09 13:23 UTC
